name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest -m "not gpu" tests/
